# Run RSpec test suite and print results.
# A job in Github Actions runs in its independent virtual environment.
# Head-Office Github Actions workflow covers these jobs:
#   (1) AppRSpecTests
#   (2) Application image deploy via AWS Elastic Beanstalk

name: deploy
# List of Github events triggering the workflow
on:
  push:
    branches:
      - main

jobs:
  # Build the Head Office Docker image, publish it to the
  # AWS Container Registry repository and trigger an Elastic Beanstalk deploy.
  DeployToGitHubPages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # Checkout branch that triggered push, ie: refs/remotes/origin/staging
          ref: ${{ github.ref }}
      - name: Setup SSH Agent
        # sets up the SSH agent, including setting the $SSH_AUTH_SOCK env variable
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GIT_PERSONAL_RSA }}
      - name: Build and push to github pages
        run: ./deploy.sh 



