# Run RSpec test suite and print results.
# A job in Github Actions runs in its independent virtual environment.
# Head-Office Github Actions workflow covers these jobs:
#   (1) AppRSpecTests
#   (2) Application image deploy via AWS Elastic Beanstalk

name: deploy
# List of Github events triggering the workflow
on:
  push:
    branches:
      - production

jobs:
  # Build the Head Office Docker image, publish it to the
  # AWS Container Registry repository and trigger an Elastic Beanstalk deploy.
  EbsAppDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # Checkout branch that triggered push, ie: refs/remotes/origin/staging
          ref: ${{ github.ref }}
      - name: Build and push to github pages
        run: |
          npm run build
          git add .
          git commit -m "deploy - add dist files"
          git subtree push --prefix dist origin gh-pages




